/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectogui;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import proyectogui.Archivos.AventuraLibro;


/**
 *
 * @author edgar
 */
public class VentanaLector extends javax.swing.JFrame {
    private JFrame ventanaPrincipal;
    private int indice;
    Reproductor reproductor = new Reproductor();
    ArrayList <AventuraLibro> listaLibros = new ArrayList<>();
    AventuraLibro Libro = new AventuraLibro();
    
    /**
     * Creates new form VentanaLector
     * @param _ventana
     * @param _listaLibros
     */
    public VentanaLector(JFrame _ventana, ArrayList _listaLibros) {
        listaLibros = _listaLibros;
        setTitle("Choose your own adventure!");
        initComponents();
        ventanaPrincipal = _ventana;
        btnEjecutar.setEnabled(false);
        lblrec.setEnabled(false);
        lblrec1.setEnabled(false);
        lblrec2.setEnabled(false);
        
        int i=0;
        while(i < listaLibros.size()){
            cmbbLista.insertItemAt(listaLibros.get(i).getTituloAventura(),i);
            i++;
        }  
    }

    public void cargarImagen(int indice){
        String rutaRelativa = Libro.getImagen();
        ImageIcon icon = new ImageIcon(getClass().getResource(rutaRelativa));
        this.lblPortada.setIcon(icon);
        this.lblPortada.setVisible(true);
        lblrec.setEnabled(true);
        lblrec2.setEnabled(true);
        lblrec1.setEnabled(true);
    }
    
    public void limpiar(){
        this.lblPortada.setEnabled(false);
        lblrec.setEnabled(false);
        lblrec2.setEnabled(false);
        lblrec1.setEnabled(false);
        txtSinopsis.setText("");
        lblEstado.setText("");
    }

    public void regresar(JFrame _ventana){
        setVisible(false);
        _ventana.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbbLista = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSinopsis = new javax.swing.JTextArea();
        lblEstado = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnEjecutar = new javax.swing.JButton();
        lblPortada = new javax.swing.JLabel();
        lblrec = new javax.swing.JLabel();
        lblrec2 = new javax.swing.JLabel();
        lblrec1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        cmbbLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbListaActionPerformed(evt);
            }
        });

        txtSinopsis.setColumns(20);
        txtSinopsis.setForeground(new java.awt.Color(255, 255, 255));
        txtSinopsis.setRows(5);
        txtSinopsis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSinopsis.setCaretColor(new java.awt.Color(0, 0, 0));
        txtSinopsis.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtSinopsis.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSinopsis.setEnabled(false);
        jScrollPane1.setViewportView(txtSinopsis);

        lblEstado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Selecciona el libro");

        btnEjecutar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEjecutar.setText("Ejecutar");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });

        lblPortada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPortada.setEnabled(false);

        lblrec.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblrec.setText("para una mejor experiencia.");

        lblrec2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectogui/Imagenes/headphones.png"))); // NOI18N

        lblrec1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblrec1.setText("Se recomienda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPortada, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblrec1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblrec2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblrec))))
                    .addComponent(cmbbLista, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbbLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPortada, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblrec, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblrec2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblrec1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbbListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbListaActionPerformed
        JComboBox<?> comboBox = (JComboBox<?>) evt.getSource();
        lblPortada.setEnabled(true);
        int selectedIndex = comboBox.getSelectedIndex();
        if (selectedIndex <= listaLibros.size()){
            Libro = listaLibros.get(selectedIndex);
            cargarImagen(selectedIndex);
            txtSinopsis.setText(Libro.getSinopsis());
            if (Libro.getEstado()){
                lblEstado.setText("Completo");
            }else{
                lblEstado.setText("Incompleto");
            }
        }
        indice = selectedIndex;
        btnEjecutar.setEnabled(true);
    }//GEN-LAST:event_cmbbListaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        regresar(ventanaPrincipal);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        this.setVisible(false);
        reproductor.reproducir("/proyectogui/Musica/base1.wav",0.9f);
        VentanaPaginas ejecutar = new VentanaPaginas(Libro,1,reproductor,this,indice);
        ejecutar.setVisible(true);
        limpiar();
        btnEjecutar.setEnabled(false);
    }//GEN-LAST:event_btnEjecutarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbbLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblPortada;
    private javax.swing.JLabel lblrec;
    private javax.swing.JLabel lblrec1;
    private javax.swing.JLabel lblrec2;
    private javax.swing.JTextArea txtSinopsis;
    // End of variables declaration//GEN-END:variables
}
