/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectogui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import proyectogui.Archivos.AventuraLibro;
import proyectogui.Archivos.ConcreteTipoNuevoInicio;
import proyectogui.Archivos.CuandoCompletasLibro;
import proyectogui.Archivos.FactoryTipoPaginas;
import proyectogui.Archivos.ObservarAventura;
import proyectogui.Archivos.Paginas;
import proyectogui.Archivos.TipoPaginas;

/**
 *
 * @author edgar
 */
public class VentanaAgregarPaginas extends javax.swing.JFrame {
    private int numero=1;
    private int i=0;
    private int indice;
    ArrayList <AventuraLibro> listaLibros = new ArrayList<>();
    AventuraLibro Libro = new AventuraLibro();
    private JFrame ventanaAutor; 
    ObservarAventura observador = new CuandoCompletasLibro("Imagenes/observer.jpg","/proyectogui/Musica/observer.wav"); 
    
    /**
     * Creates new form VentanaAgregarPaginas
     * @param _ventana
     * @param _listaLibros
     */
    public VentanaAgregarPaginas(JFrame _ventana, ArrayList _listaLibros) {
        listaLibros = _listaLibros;
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent windowEvent) {
                ventanaAutor.setVisible(true);
            }
        });
        ventanaAutor = _ventana;
        initComponents();
        
        
        int j=0;
        while(j < listaLibros.size()){
            cmbbLista.insertItemAt(listaLibros.get(j).getTituloAventura(),j);
            j++;
        }
        
    }

    
    public void regresar(JFrame _ventana){
        setVisible(false);
        _ventana.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbbLista = new javax.swing.JComboBox<>();
        lblTxt1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContenido = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtNumPag = new javax.swing.JTextField();
        cmbbTipoPag = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtOp2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIrOp2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtOp1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtIrOp1 = new javax.swing.JTextField();
        btnAgregarPaginas = new javax.swing.JButton();
        lblAdvertencia = new javax.swing.JLabel();
        lblPaginas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(620, 570));
        setResizable(false);
        setSize(new java.awt.Dimension(620, 570));

        cmbbLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbListaActionPerformed(evt);
            }
        });

        lblTxt1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTxt1.setText("Selecciona el libro");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Contenido");

        txtContenido.setColumns(20);
        txtContenido.setRows(5);
        jScrollPane1.setViewportView(txtContenido);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Pagina");

        txtNumPag.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNumPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumPagActionPerformed(evt);
            }
        });

        cmbbTipoPag.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbbTipoPag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        cmbbTipoPag.setSelectedIndex(-1);
        cmbbTipoPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbTipoPagActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("TipoPagina");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Lleva a ->");

        txtOp2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Opcion 2");

        txtIrOp2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Opcion 1");

        txtOp1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Lleva a ->");

        txtIrOp1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        btnAgregarPaginas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAgregarPaginas.setText("Agregar");
        btnAgregarPaginas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPaginasActionPerformed(evt);
            }
        });

        lblAdvertencia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAdvertencia.setForeground(new java.awt.Color(255, 0, 0));

        lblPaginas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIrOp2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(133, 133, 133))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cmbbLista, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumPag, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 74, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbbTipoPag, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblPaginas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIrOp1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregarPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(lblAdvertencia, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOp1)
                            .addComponent(jScrollPane1)
                            .addComponent(txtOp2))
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPaginas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbbLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNumPag, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbbTipoPag, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIrOp1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtOp1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIrOp2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtOp2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgregarPaginas, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(lblAdvertencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbbListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbListaActionPerformed
        JComboBox<?> comboBox = (JComboBox<?>) evt.getSource();
        int selectedIndex = comboBox.getSelectedIndex();
        if (selectedIndex <= listaLibros.size()){
            System.out.println("indice seleccionado: "+selectedIndex);
            Libro = listaLibros.get(selectedIndex);
        }      
    }//GEN-LAST:event_cmbbListaActionPerformed

    private void btnAgregarPaginasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPaginasActionPerformed
        TipoPaginas tipoPag;
        FactoryTipoPaginas fabrica;
        fabrica = new ConcreteTipoNuevoInicio();
        tipoPag = fabrica.crearFinal(numero);
        i = Integer.parseInt(txtNumPag.getText());
        
        
        Libro.getPaginas().get(i).setContenido(txtContenido.getText());
        Libro.getPaginas().get(i).setNumero(Integer.parseInt(txtNumPag.getText()));
        Libro.getPaginas().get(i).setOp1(txtOp1.getText());
        Libro.getPaginas().get(i).setOp2(txtOp2.getText());
        Libro.getPaginas().get(i).setImagen("Imagenes/Fondo2.jpeg");
        Libro.getPaginas().get(i).setTipopaginas(tipoPag);
        Libro.getPaginas().get(i).setSonidoOp1("/proyectogui/Musica/pasos.wav");
        Libro.getPaginas().get(i).setSonidoOp2("/proyectogui/Musica/pasos.wav");
        
        if(tipoPag.getTipo() == 1){
            Libro.getPaginas().get(i).setOp1(txtOp1.getText());
            Libro.getPaginas().get(i).setOp2(txtOp2.getText());
            Libro.getPaginas().get(i).setNodo1(Integer.parseInt(txtIrOp1.getText()));
            Libro.getPaginas().get(i).setNodo2(Integer.parseInt(txtIrOp2.getText()));            
        }if(tipoPag.getTipo() == 2){
            Libro.getPaginas().get(i).setOp1("Continuar");
            Libro.getPaginas().get(i).setOp2(null);
            Libro.getPaginas().get(i).setNodo1(1);
            Libro.getPaginas().get(i).setNodo2(2);           
        }if(tipoPag.getTipo() == 3){
            Libro.getPaginas().get(i).setOp1(null);
            Libro.getPaginas().get(i).setOp2(null);
            Libro.getPaginas().get(i).setNodo1(0);
            Libro.getPaginas().get(i).setNodo2(0);
        }
        regresar(ventanaAutor);
        
        
    }//GEN-LAST:event_btnAgregarPaginasActionPerformed

    private void cmbbTipoPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbTipoPagActionPerformed
        JComboBox<?> comboBox = (JComboBox<?>) evt.getSource();
        int selectedIndex = comboBox.getSelectedIndex();
        if(selectedIndex == 0){
            lblPaginas.setText("Nodo");
            numero = 1;
        }if(selectedIndex == 1){
            lblPaginas.setText("Nuevo");
            numero = 2;
        }if(selectedIndex == 2){
            lblPaginas.setText("Final");
            numero = 3;
        }
    }//GEN-LAST:event_cmbbTipoPagActionPerformed

    private void txtNumPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumPagActionPerformed
        i = Integer.parseInt(txtNumPag.getText());
        System.out.println("i = "+i);
    }//GEN-LAST:event_txtNumPagActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPaginas;
    private javax.swing.JComboBox<String> cmbbLista;
    private javax.swing.JComboBox<String> cmbbTipoPag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdvertencia;
    private javax.swing.JLabel lblPaginas;
    private javax.swing.JLabel lblTxt1;
    private javax.swing.JTextArea txtContenido;
    private javax.swing.JTextField txtIrOp1;
    private javax.swing.JTextField txtIrOp2;
    private javax.swing.JTextField txtNumPag;
    private javax.swing.JTextField txtOp1;
    private javax.swing.JTextField txtOp2;
    // End of variables declaration//GEN-END:variables
}
